# Generated by Django 5.1.4 on 2025-01-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('runtime_in_minutes', models.PositiveIntegerField()),
            ],
        ),
    ]
